name: First workflow
on: workflow_dispatch 	
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: print greeting 
      run: echo "hey!"
    - name: print goodbye
      run: echo "gudbye!"
